
build:
  image: distribot/drone
  commands:
    - ./provision/nodes.sh
    - sudo apt-get update
    - sudo apt-get install -y git
    - gem install bundler --no-ri --no-rdoc
    - bundle
    - bundle exec rspec
  environment:
    - INFRA_HOST=127.0.0.1
    - RABBITMQ_USERNAME=distribot
    - RABBITMQ_PASSWORD=distribot

compose:
  infra:
    image: distribot/infra:latest
    commands:
      - ./provision/infra.sh
      - tail -f /dev/null
