
infra:
  image: distribot/infra
  # build: .
  # dockerfile: ./Dockerfile
  volumes:
    - ./:/var/www/distribot
  environment:
    - TERM=xterm
    - RABBITMQ_USERNAME=distribot
    - RABBITMQ_PASSWORD=distribot
  working_dir: /var/www/distribot
  command: bash -c "./provision/infra.sh && tail -f /dev/null"
  # "
  ports:
    - 5672
    - 15672
    - 6379
    - 443

engine:
  image: distribot/node
  # build: .
  # dockerfile: ./Dockerfile
  volumes:
    - ./:/var/www/distribot
  environment:
    - TERM=xterm
    - INFRA_HOST=infra_1
    - RABBITMQ_USERNAME=distribot
    - RABBITMQ_PASSWORD=distribot
  working_dir: /var/www/distribot
  links:
    - infra
  command: bash -c "./provision/nodes.sh && eye load examples/distribot.eye && sudo tail -f /var/log/td-agent/td-agent.log"

worker:
  image: distribot/node
  # build: .
  # dockerfile: ./Dockerfile
  volumes:
    - ./:/var/www/distribot
  environment:
    - TERM=xterm
    - INFRA_HOST=infra_1
    - RABBITMQ_USERNAME=distribot
    - RABBITMQ_PASSWORD=distribot
  working_dir: /var/www/distribot
  links:
    - infra
  command: bash -c "./provision/nodes.sh && sudo tail -f /var/log/td-agent/td-agent.log"
  # "

controller:
  image: distribot/node
  # build: .
  # dockerfile: ./Dockerfile
  volumes:
    - ./:/var/www/distribot
  environment:
    - TERM=xterm
    - INFRA_HOST=infra_1
    - RABBITMQ_USERNAME=distribot
    - RABBITMQ_PASSWORD=distribot
  working_dir: /var/www/distribot
  links:
    - infra
  command: bash -c "./provision/nodes.sh && sudo tail -f /var/log/td-agent/td-agent.log"
