#!/usr/bin/env ruby

require 'pp'
require 'securerandom'
require 'bunny'
require 'byebug'
require 'active_support/json'

module QQ

  class Connector
    attr_accessor :connection_args, :bunny, :channel
    def initialize(connection_args={})
      self.connection_args = connection_args
      self.bunny = Bunny.new(self.connection_args)
      self.bunny.start
      self.channel = self.bunny.create_channel
      self.channel.prefetch(1)
    end
  end

  class ConnectionSharer
    attr_accessor :bunny, :channel
    def initialize(bunny)
      self.bunny = bunny
      self.channel = self.bunny.create_channel
    end
  end

  class Subscription < ConnectionSharer
    attr_accessor :consumer
    def start(topic, options={}, &block)
      queue = self.channel.queue(topic, auto_delete: true, durable: true)
      self.consumer = queue.subscribe(options.merge(manual_ack: true)) do |delivery_info, properties, payload|
        begin
          parsed_message = JSON.parse(payload, symbolize_names: true)
          block.call( parsed_message )
          self.channel.acknowledge(delivery_info.delivery_tag, false)
        rescue StandardError => e
          puts "ERROR: #{e} -- #{e.backtrace.join("\n")}"
          self.channel.basic_reject(delivery_info.delivery_tag, true)
        end
      end
      self
    end

    def cancel
      self.consumer.cancel
      self.channel.close
    end
  end

  class MultiSubscription < ConnectionSharer
    def start(topic, options={}, &block)
      private_queue = self.channel.queue('', exclusive: true, auto_delete: true)
      exchange = self.channel.fanout(topic)
      private_queue.bind(exchange).subscribe(options) do |delivery_info, properties, payload|
      begin
        block.call(JSON.parse(payload, symbolize_names: true))
      rescue StandardError => e
        puts "Error #{e} with #{payload} --- #{e.backtrace.join("\n")}"
      end
      end
    end
  end

  class Client < Connector
    attr_accessor :subscribers, :multi_subscribers
    def initialize(*args)
      super(*args)
      self.subscribers = [ ]
      self.multi_subscribers = [ ]
      self.bunny = Bunny.new(self.connection_args)
      self.bunny.start
      self.channel = self.bunny.create_channel
    end

    def subscribe(topic, options={}, &block)
      subscriber = Subscription.new(self.bunny)
      self.subscribers << subscriber.start(topic, options) do |message|
        block.call( message )
      end
    end

    def subscribe_multi(topic, options={}, &block)
      subscriber = MultiSubscription.new(self.bunny)
      self.multi_subscribers << subscriber.start(topic, options) do |message|
        block.call( message )
      end
    end

    def publish(topic, message)
      queue = self.channel.queue(topic, auto_delete: true, durable: true)
      self.channel.default_exchange.publish message.to_json, routing_key: topic
    end

    def broadcast(topic, message)
      exchange = self.channel.fanout(topic)
      exchange.publish(message.to_json, routing_key: topic)
    end
  end
end

qq = QQ::Client.new({})

MAX_WORKERS = ARGV.shift.to_i
MAX_MESSAGES = ARGV.shift.to_i

MAX_WORKERS.times do |worker_id|
  qq.subscribe('foo') do |msg|
    latency = Time.now.to_f - msg[:published_at]
    puts "GOT SINGLE ##{worker_id} #{msg[:message]} latency:#{latency.round(3)} sec since #{msg[:published_at]}"
    sleep rand / 10
  end

  qq.subscribe_multi('hotline') do |msg|
    latency = Time.now.to_f - msg[:published_at]
    puts "GOT MULTI ##{worker_id} #{msg[:message]} latency:#{latency.round(3)} sec since #{msg[:published_at]}"
    sleep rand / 10
  end
end

#MAX_MESSAGES.times do |n|
batch = 0
while true do
  100.times do |item|
    qq.publish('foo', {hello: "world", message: "#{batch}.#{item}", published_at: Time.now.to_f})
    if item % 10 == 0
      qq.broadcast('hotline', {hello: "world", message: "#{batch}.#{item}", published_at: Time.now.to_f})
    end
  end
  batch += 1
  # puts "-------------------------------------------------- SLEEP ---------------------"
  sleep 0.2
end

sleep





