#!/usr/bin/env ruby

require 'distribot'
require 'byebug'

redis = Distribot.redis
while true do
  redis.smembers('distribot.workflows.active').sort.each do |id|
    workflow = Distribot::Workflow.find( id )
    latest_transition = workflow.transitions.last
    latest_phase = workflow.phase(latest_transition.to) || Distribot::Phase.new(name: "UNKNOWN")
    next if latest_phase.is_final
    time_in_phase = Time.now.to_f - latest_transition.timestamp

    puts "Workflow #{workflow.id} is " << if latest_phase.is_final
      "FINISHED!"
    else
      "STILL ON PHASE #{latest_phase.name} (#{time_in_phase.round(2)} seconds"
    end
  end
  puts "\n\n"
  sleep 1
end
