#!/usr/bin/env ruby

require 'bundler/setup'
require 'distribot'
require 'byebug'
require 'pp'
require 'active_support/core_ext/object'
require 'active_support/core_ext/array'
require 'active_support/json'
require 'dotenv'

Dotenv.load

Distribot.configure do |config|
  config.redis_url = ENV['DISTRIBOT_REDIS_URL']
  config.rabbitmq_url = ENV['DISTRIBOT_RABBITMQ_URL']
end

class SimpleWorker
  include Distribot::Worker
  enumerate_with :enumerate
  process_tasks_with :process

  def enumerate(context, &callback)
    jobs = [ ]

    2.times do |chunk|
      max = 10
      jobs << (1..max).to_a.map{|n| {id: SecureRandom.uuid, args: [chunk, n] } }
    end
#sleep 0.5
    callback.call(jobs.flatten)
  end

  def process(context, job)
#raise "Test Error" if rand * 100 < 10
puts job
#    puts "Processing job '#{context.workflow_id}.#{context.phase}.#{self} #{job[:args]}'"
#    sleep 0.5
  end
end

class HardWorker < SimpleWorker; end
class GoodWorker < SimpleWorker; end
class FastWorker < SimpleWorker; end
class CheapWorker < SimpleWorker; end
class ForeignWorker < SimpleWorker; end
class SlowWorker < SimpleWorker; end

puts HardWorker.new.run
puts GoodWorker.new.run
puts FastWorker.new.run
puts CheapWorker.new.run
puts ForeignWorker.new.run
puts SlowWorker.new.run

sleep
