
# build with docker build -t distribot/alpine:0.3.0 -f .docker/Dockerfile.thin .

FROM ruby:2.2-alpine

RUN \
  apk --no-cache add curl \
  && gem install distribot --no-ri --no-rdoc \
  && gem install foreman --no-ri --no-rdoc

COPY Procfile /Procfile
COPY .docker/entrypoint.thin.sh /entrypoint.sh
WORKDIR /
ENTRYPOINT ["/entrypoint.sh"]
